spring.application.name=module2
spring.h2.console.enabled=true

#In disk database
spring.datasource.url=jdbc:h2:file:D:/Learnings/InDiskDb
spring.datasource.username=abhiDb
spring.datasource.password=Admin12345
spring.jpa.hibernate.ddl-auto=none